Get Users object
mpociot/blacksmith pull request #4
Opened 2016-11-18 14:49 UTC by petericebear

This is for getting the forge_token for generating the provisions request later

2016-11-18 14:52 UTC, mpociot commented
It would be better if we handle this like the other API calls and return a `User` object instead of a plain array.

2016-11-18 14:58 UTC, petericebear commented
Ah yes. Will change it and create a new pull-request..

2016-11-18 15:04 UTC, mpociot commented
You can just update this one if you want 👍

2016-11-18 15:14 UTC, petericebear commented
It returns the full User object

2016-11-18 15:19 UTC, djekl requested changes

2016-11-18 15:19 UTC, djekl commented on src/Mpociot/Blacksmith/Models/User.php
> +    public function toArray()
Why does this function exist in the `User` model. Its already in the extended `ForgeModel` and does the exact same. Its OK to have an empty model. It looks to me like you have copied the `Server` model, which also needs it removing from.

2016-11-18 15:29 UTC, petericebear commented on src/Mpociot/Blacksmith/Models/User.php
> +    public function toArray()
Good point, I removed it.. Yes I copied it from another file.
Currently working on (custom) server creation function and needed the User object first

2016-11-19 11:51 UTC, petericebear commented
@mpociot I added a new function of issue #1 .. Server creation, and updated readme with an example for creation a custom load balancer.

2016-11-19 11:55 UTC, merged

2016-11-19 11:55 UTC, mpociot commented
Thank you!